/// @description Initialize
depth = -6000;
image_speed = 0;
image_index = 0;

leftClick = false;
leftScript = -1;
leftArgs = -1;
rightClick = false;
rightScript = -1;
rightArgs = -1;
text = "";
baseColor = c_black;
highlightColor = c_yellow;
textColor = c_black;
textOffsetY = 0;
focus = false;
focus_override = false;
press = false;
press_override = false;
gui = false;
enabled = true;
